# Generated by Django 5.2 on 2025-04-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='auth',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='p256dh',
            field=models.CharField(max_length=200),
        ),
    ]
