# Generated by Django 4.2.20 on 2025-04-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='task_time_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='task_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
