# Generated by Django 4.2.20 on 2025-04-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0006_alter_pushsubscription_auth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='task_title',
            field=models.CharField(default='Unknown', max_length=500),
        ),
    ]
